version: '3.8'
services:
  vendas-db:
    image: postgres:latest
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
    - dikendev
networks:
  dikendev:  
